export const cities = [
  { label: "Tel Aviv" },
  { label: "Jerusalem" },
  { label: "Tokyo" },
  { label: "Delhi" },
  { label: "Shanghai" },
  { label: "Sao Paulo" },
  { label: "Mexico City" },
  { label: "Cairo" },
  { label: "Mumbai" },
  { label: "Beijing" },
  { label: "Dhaka" },
  { label: "Osaka" },
  { label: "New York" },
  { label: "Karachi" },
  { label: "Buenos Aires" },
  { label: "Istanbul" },
  { label: "Kolkata" },
  { label: "Manila" },
  { label: "Lagos" },
  { label: "Rio de Janeiro" },
  { label: "Tianjin" },
  { label: "Kinshasa" },
  { label: "Guangzhou" },
  { label: "Los Angeles" },
  { label: "Moscow" },
  { label: "Shenzhen" },
  { label: "Lahore" },
  { label: "Bangalore" },
  { label: "Paris" },
  { label: "Bogota" },
  { label: "Jakarta" },
  { label: "Chennai" },
  { label: "Lima" },
  { label: "Bangkok" },
  { label: "Seoul" },
  { label: "Nagoya" },
  { label: "Hyderabad" },
  { label: "London" },
  { label: "Tehran" },
  { label: "Chicago" },
  { label: "Chengdu" },
  { label: "Nanjing" },
  { label: "Wuhan" },
  { label: "Ho Chi Minh City" },
  { label: "Luanda" },
  { label: "Ahmedabad" },
  { label: "Kuala Lumpur" },
  { label: "Hangzhou" },
  { label: "Hong Kong" },
  { label: "Quanzhou" },
  { label: "Ezhou" },
  { label: "Changsha" },
  { label: "Foshan" },
  { label: "New Taipei City" },
  { label: "Shijiazhuang" },
  { label: "Hanoi" },
  { label: "Suzhou" },
  { label: "Dongguan" },
  { label: "Jinan" },
  { label: "Nanning" },
  { label: "Zhengzhou" },
  { label: "Taiyuan" },
  { label: "Kunming" },
  { label: "Taipei" },
  { label: "Shenyang" },
  { label: "Changchun" },
  { label: "Xiamen" },
  { label: "Changzhou" },
  { label: "Dalian" },
];
